### ISSUE TITLE
Confusion about apperance feature size

### ISSUE THREAD

**Issue by Gaoyiminggithub** [Dong-JinKim/ActionCooccurrencePriors#5]
Thanks for your beautiful work.
I used the appearance features provided by No-Frills Human-Object Interaction Detection: Factorization, Layout Encodings, and Training Techniques. However, I run the code but got an error of size mismatch.
I find the appearance feature size in your work is set to 1024, while is different with No-Frills (No-Frills appearance feature size is set to 2048). Is it correct?
Thank you again for your attention!

**Comment by CodeOfKkkkken0502** [comment]
I have the same confusion, too. Could you tell me how did you fix this mismatch problem? Thanks a lot!

**Comment by Gaoyiminggithub** [comment]
Hi @CodeOfKkkkken0502, I finally use the appearance features provided by the authors.

**Comment by CodeOfKkkkken0502** [comment]
Thanks for your answer.
I'm trying to implement an HOI detector based on this work, which takes an image as input. So I need to figure out how to fix the mismatch, in order to connect the object detector with the proposed network.
I'm wondering if there is a method to transform the 2048-dim fc7 feature into 1024-dim fc7 feature. If you know any method like this, please let me know. Thank you. :)
